tabWidth: 4
semi: false
singleQuote: false
useTabs: true
overrides:
    - files: "*.yml"
      options:
          tabWidth: 2
          useTabs: false
    - files: "*.py"
      options:
          tabWidth: 4
          useTabs: true
          semi: false
          singleQuote: true
    - files:
          - "*.js"
          - "*.jsx"
          - "*.ts"
          - "*.tsx"
      options:
          tabWidth: 4
          useTabs: true
          semi: false
          singleQuote: false
